language: android

jdk: openjdk7

android:
  components:
    - tools
    - platform-tools-preview
    - build-tools-23.0.0-preview
    - extra-android-support
    - extra-android-m2repository
    - android-22

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew clean assembleDebug
